#!/bin/bash
#
# Copyright 2021 Hewlett Packard Enterprise Development LP. All rights reserved.
#

CONFIG_DIR=@CONFIG_DIR@

set -x
set -e

mst start
mst status -v

while read -r device_type device_id pci_id rdma_id numa_region || [[ -n "$line" ]] ; do
	if [[ -z $pci_id ]] ; then
		# skip -- this PCI device couldn't be recognized
		continue
	fi

	PSID=$(flint -d $device_id query | grep PSID | awk '{print $2}')
	DEVICE_CONFIG_DIR=$CONFIG_DIR/$PSID

	if [[ ! -d $DEVICE_CONFIG_DIR ]] ; then
		# skip -- this PSID is an unmanaged PSID
		continue
	fi

	CONF_FILE=$DEVICE_CONFIG_DIR/config.new

	mlxconfig -d $device_id -f /tmp/config.new backup
	mlxconfig -d $device_id raw2xml /tmp/config.new /tmp/config.xml
	mv /tmp/config.xml /tmp/$PSID-${pci_id}_config.xml
	rm /tmp/config.new
done < <(mst status -v | grep "/dev" | grep pciconf)
